version: "3.2"

services:

  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/app/:/app
      - /app/node_modules
      #- ./frontend/app/node_modules:/app/node_modules:rw
    ports:
      - 3001:3000
      - 35729:35729
    depends_on: 
      - backend

  backend: 
    build: ./backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend/app/:/app    
    ports: 
      - 3000:8001
