version: "3.2"

services:

  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/app/:/app
      
    ports:
      - 3001:3000
      - 35729:35729
    depends_on: 
      - backend

  backend: 
    build: ./backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend/app/:/app    
    ports: 
      - 3000:8001
